"""Extract PasarGuard / Marzban-lineage data (SQLite or pre-parsed SQL tables)."""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

from app.services.importing.types import ImportGroupDraft, ImportHostDraft, ImportPlan, ImportSource, ImportUserDraft
from app.services.importing.util import as_datetime, parse_json_obj, sanitize_username


def _truthy(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if value in (None, "", 0, "0", "f", "false", "False", "n"):
        return False
    return bool(value)


def _as_opt_int(val: Any) -> int | None:
    if val in (None, ""):
        return None
    try:
        return int(val)
    except (TypeError, ValueError):
        return None


def plan_from_tables(
    tables: dict[str, list[dict[str, Any]]],
    *,
    source_note: str | None = None,
) -> ImportPlan:
    """Build an ImportPlan from table→rows (SQLite or SQL-dump parsed)."""
    plan = ImportPlan(source=ImportSource.pasarguard)
    plan.notes.append("Subscription URLs will be regenerated by HPXPANEL (JWT/user id).")
    plan.notes.append("Nodes are not imported — re-add and pair nodes after import.")
    plan.notes.append("Data is merged into your current HPX database (Timescale/Postgres/MySQL/SQLite).")
    if source_note:
        plan.notes.append(source_note)

    group_id_to_name: dict[int, str] = {}
    group_id_to_tags: dict[int, list[str]] = {}

    for row in tables.get("groups", []):
        gid = int(row.get("id") or 0)
        name = sanitize_username(str(row.get("name") or f"group-{gid}"), fallback=f"group-{gid}")
        if len(name) < 3:
            name = f"grp-{name}"
        group_id_to_name[gid] = name
        group_id_to_tags[gid] = []
        plan.groups.append(
            ImportGroupDraft(
                name=name,
                inbound_tags=[],
                is_disabled=_truthy(row.get("is_disabled")),
                source_id=gid,
            )
        )

    inbound_id_to_tag: dict[int, str] = {}
    for row in tables.get("inbounds", []):
        try:
            iid = int(row["id"])
        except (KeyError, TypeError, ValueError):
            continue
        inbound_id_to_tag[iid] = str(row.get("tag") or row.get("id"))

    for row in tables.get("inbounds_groups_association", []):
        try:
            gid = int(row.get("group_id") or 0)
            iid = int(row.get("inbound_id") or 0)
        except (TypeError, ValueError):
            continue
        tag = inbound_id_to_tag.get(iid)
        if tag and gid in group_id_to_tags:
            group_id_to_tags[gid].append(tag)

    for draft in plan.groups:
        if draft.source_id is not None:
            draft.inbound_tags = list(dict.fromkeys(group_id_to_tags.get(draft.source_id, [])))

    user_id_to_group_names: dict[int, list[str]] = {}
    for row in tables.get("users_groups_association", []):
        try:
            uid = int(row.get("user_id") or 0)
            gid = int(row.get("group_id") or 0)
        except (TypeError, ValueError):
            continue
        gname = group_id_to_name.get(gid)
        if gname:
            user_id_to_group_names.setdefault(uid, []).append(gname)

    users = tables.get("users", [])
    if not users:
        plan.warnings.append("No users table/rows found in PasarGuard data")
        return plan

    for row in users:
        username = sanitize_username(str(row.get("username") or ""))
        if not username:
            plan.warnings.append("Skipped user with empty username")
            continue
        proxy_settings = parse_json_obj(row.get("proxy_settings"), {})
        if not isinstance(proxy_settings, dict):
            proxy_settings = {}

        status = str(row.get("status") or "active").lower()
        if status not in {"active", "disabled", "on_hold", "limited", "expired"}:
            status = "active"

        expire = as_datetime(row.get("expire")) if "expire" in row else None

        try:
            used = int(row.get("used_traffic") or 0)
        except (TypeError, ValueError):
            used = 0
        data_limit = row.get("data_limit")
        try:
            data_limit_i = int(data_limit) if data_limit not in (None, "") else None
        except (TypeError, ValueError):
            data_limit_i = None
        if data_limit_i == 0:
            data_limit_i = None

        try:
            uid = int(row.get("id") or 0)
        except (TypeError, ValueError):
            uid = 0

        plan.users.append(
            ImportUserDraft(
                username=username,
                proxy_settings=proxy_settings,
                status=status if status in {"active", "disabled", "on_hold"} else "active",
                data_limit=data_limit_i,
                used_traffic=max(0, used),
                expire=expire,
                note=(str(row["note"])[:500] if row.get("note") else None),
                on_hold_expire_duration=_as_opt_int(row.get("on_hold_expire_duration")),
                data_limit_reset_strategy=(
                    str(row["data_limit_reset_strategy"]) if row.get("data_limit_reset_strategy") else None
                ),
                hwid_limit=_as_opt_int(row.get("hwid_limit")),
                ip_limit=_as_opt_int(row.get("ip_limit")),
                source_group_names=list(user_id_to_group_names.get(uid, [])),
                meta={"source_user_id": uid},
            )
        )

    for idx, row in enumerate(tables.get("hosts", [])):
        remark = str(row.get("remark") or f"host-{idx + 1}")
        address_raw = row.get("address")
        addresses: set[str] = set()
        if isinstance(address_raw, str) and address_raw.strip():
            parsed = parse_json_obj(address_raw, None)
            if isinstance(parsed, list):
                addresses = {str(a).strip() for a in parsed if str(a).strip()}
            else:
                addresses = {p.strip() for p in address_raw.split(",") if p.strip()}
        elif address_raw:
            addresses = {str(address_raw)}

        inbound_tag = None
        if row.get("inbound_tag"):
            inbound_tag = str(row["inbound_tag"])
        elif row.get("inbound_id") not in (None, ""):
            try:
                inbound_tag = inbound_id_to_tag.get(int(row["inbound_id"]))
            except (TypeError, ValueError):
                inbound_tag = None

        sni_raw = parse_json_obj(row.get("sni"), None)
        host_raw = parse_json_obj(row.get("host"), None)
        sni = {str(x) for x in sni_raw} if isinstance(sni_raw, list) else set()
        host_hdr = {str(x) for x in host_raw} if isinstance(host_raw, list) else set()
        if isinstance(row.get("sni"), str) and not sni:
            sni = {p.strip() for p in str(row["sni"]).split(",") if p.strip()}
        if isinstance(row.get("host"), str) and not host_hdr:
            host_hdr = {p.strip() for p in str(row["host"]).split(",") if p.strip()}

        port = row.get("port")
        try:
            port_i = int(port) if port not in (None, "") else None
        except (TypeError, ValueError):
            port_i = None
        try:
            priority = int(row["priority"]) if row.get("priority") not in (None, "") else idx
        except (TypeError, ValueError):
            priority = idx

        plan.hosts.append(
            ImportHostDraft(
                remark=remark or f"imported-host-{idx + 1}",
                address=addresses or {"127.0.0.1"},
                inbound_tag=inbound_tag,
                port=port_i,
                sni=sni,
                host=host_hdr,
                path=str(row["path"]) if row.get("path") else None,
                security=str(row.get("security") or "inbound_default"),
                allowinsecure=_truthy(row["allowinsecure"]) if row.get("allowinsecure") is not None else None,
                is_disabled=_truthy(row.get("is_disabled")),
                priority=priority,
            )
        )

    if not plan.users:
        plan.warnings.append("No users extracted from PasarGuard database")
    return plan


def extract_pasarguard(db_path: Path) -> ImportPlan:
    """Extract from a PasarGuard SQLite file."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        names = {
            str(r[0]).lower()
            for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
        }
        tables: dict[str, list[dict[str, Any]]] = {}
        for table in (
            "users",
            "groups",
            "hosts",
            "inbounds",
            "users_groups_association",
            "inbounds_groups_association",
        ):
            if table not in names:
                continue
            cur = conn.execute(f"SELECT * FROM {table}")
            cols = [d[0] for d in cur.description]
            tables[table] = [dict(zip(cols, row, strict=False)) for row in cur.fetchall()]
    finally:
        conn.close()
    return plan_from_tables(tables, source_note=f"Source file: {db_path.name} (SQLite)")
